#!/bin/sh

# shameless copied from:
# http://stackoverflow.com/questions/7814612/is-there-any-way-to-redraw-tmux-window-when-switching-smaller-monitor-to-bigger

tmtakeover() {
  # create a temporary session that displays the "how to go back" message
  tmp='tmtakeover temp session'
  if ! tmux has-session -t "$tmp"; then
    tmux new-session -d -s "$tmp"
    tmux set-option -t "$tmp" set-remain-on-exit on
    tmux new-window -kt "$tmp":0 'echo "Use Prefix+L to return to session."'
  fi


  # switch any clients attached to the target session to the temp session
  session="$1"
  for client in $(tmux list-clients -t "$session" | cut -f 1 -d :); do
    tmux switch-client -c "$client" -t "$tmp"
  done

  # attach to the target session
  tmux attach -t "$session"
}

